generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProfilePermission
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profile_permission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~      
      fields:
      form:
        display:           
         "Details":        [name, description]
      list:
        title:             Profile Permissions
        display:           [=name, description]
        batch_actions:     []
        max_per_page:      10
        actions:
          _new:            ~
      edit:
        title:             Edit Profile Permission - %%name%%
        actions:
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Profile Permission
        actions:
          cancel:          []
          _save:           []