generator:
  class: sfDoctrineGenerator
  param:
    model_class:           File
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          file
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        generated_name:    { label: File }        
      actions: ~
      list:    ~
      filter:  ~
      form:    ~      
      edit:
        actions:
          _delete:         []
          cancel:          []
          done:            []
          _save:           []
      new:
        actions:
          cancel:          []
          _save:           []