# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_guard_plugin:
    routes_register: false
  popup:
    academic_period_width: 500
    academic_year_width: 500
    activity_template_width: 600
    announcement_width: 730
    application_width: 500
    assignment_width: 500
    assignment_group_width: 500
    building_width: 500
    calendar_width: 500
    calendar_event_width: 730
    calendar_event_attendee_width: 500
    contact_width: 600
    country_width: 500
    course_width: 500
    course_link_width: 500
    course_discussion_width: 600
    course_meeting_time_width: 500
    course_reading_item_width: 500
    campus_width: 500
    department_width: 500
    discussion_width: 600
    discussion_topic_width: 600
    discussion_member_width: 600
    discussion_reply_width: 500
    file_width: 500
    folder_width: 500
    email_template_width: 600
    faculty_width: 600
    gradebook_item_width: 500
    gradebook_scale_width: 500
    instructor_width: 600
    mailing_list_width: 700
    menu_item_width: 600
    message_width: 600
    news_width: 730
    program_width: 600
    program_level_width: 600
    room_width: 600
    sfGuardUser_width: 600
    sfGuardGroup_width: 600
    sfGuardPermission_width: 600
    state_province_width: 500
    contact_student_width: 600
    student_width: 600
    
  # primary level menu to module mappings
  menu_item_level_1:
    academic_info: academics
    academic_year: academics
    academic_period: academics
    activity_template: communication
    activity_feed: dashboard
    admission_statistics: admissions
    announcement: academics
    assignment: academics2
    assignment_group: academics2
    application: admissions
    building: settings
    bulletin_board: profile
    calendar: dashboard2
    calendar_event: dashboard2
    campus: settings
    country: settings
    course: academics
    course_link: academics2
    course_meeting_time: academics2
    dashboard: dashboard
    folder: folder
    department: academics
    discussion: dashboard
    email: dashboard
    email_template: communication
    faculty: academics
    financial: profile
    info: academics
    gradebook: academics
    group: dashboard
    instructor: academics
    mailing_list: communication
    menu_item: settings
    message: dashboard
    news: academics
    profile: profile
    program: academics
    program_level: academics
    registration: profile
    room: settings
    sfGuardGroup: settings
    sfGuardPermission: settings
    sfGuardUser: settings
    state_province: settings
    contact_student: academics
    student: academics
    to_do: dashboard
    
  # secondary level menu to module mappings
  menu_item_level_2:
    academic_info: general_info
    academic_year: general_settings
    academic_period: general_settings
    activity_template: messaging_settings
    assignment: course_home
    announcement: general_info
    assignment_group: course_home
    application: admission_statistics
    building: location_settings
    calendar: my_dashboard
    calendar_event: calendar_home
    discussion: home
    campus: location_settings
    country: location_settings
    course: general_info
    course_link: academics
    course_meeting_time: academics
    dashboard: my_dashboard
    document: file_system
    department: general_settings
    email: my_dashboard
    email_template: messaging_settings
    faculty: general_settings
    gradebook: general_info
    info: academics
    instructor: general_info
    menu_item: system_settings
    mailing_list: messaging_settings
    program: general_settings
    program_level: general_settings
    my_profile: profile
    my_calendar: home
    news: general_info
    room: location_settings
    sfGuardGroup: system_settings
    sfGuardPermission: system_settings
    sfGuardUser: system_settings
    state_province: location_settings
    student: general_info
    contact_student: general_info
    to_do: my_dashboard