generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Announcement
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          announcement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user:                   { label: Announcer }      
        message:                { label: Announcement }
      filter:
        class: false
      list:
        title:                  Announcements
        display:                [ user, subject ]
        sort:                   [ subject, asc ]
        batch_actions:          []
        object_actions:        
          _edit: ~
          _delete: ~
        max_per_page:	        10
        actions:
          _new:                 { label: "+ Add Announcement" }
      form:
      form:
        display:                [ subject, message, lock_until, lock_after, is_published ]
      edit:
        actions:          
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []
