generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AcademicPeriod
    theme:                 popup
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          academic_period
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        period:            { label: Period }
      filter:
        class: false
      list:
        title:             Academic Periods
        display:           [ academic_year, name, period, grades_due]
        sort:              [ name, start_date, end_date, asc ]
        batch_actions:     [ ]
        max_per_page:      10 
        actions:
          _new: ~
      edit:
        actions:
          cancel:            []
          done:              []
          _save:             []
      new:
        actions:
          cancel:            []
          _save:             []