<?php

/**
 * AcademicPeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AcademicPeriod extends BaseAcademicPeriod {

    public function __toString() {
        return (string) $this->getYearRange() . " (" . $this->getName() . ")";
    }

    public function getYearRange() {
        return $this->getAcademicYear()->getYearRange();
    }

    function getPeriod() {
        return $this->getDateTimeObject('start_date')->format('d/m/Y') . " - " . $this->getDateTimeObject('end_date')->format('d/m/Y');
    }

}