<?php

/**
 * AcademicYearTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcademicYearTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcademicYearTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcademicYear');
    }
}