<?php

/**
 * ActivityFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityFeedTable extends Doctrine_Table {

    const TYPE_SENT_PEER_INVITATION = 0;
    const TYPE_ACCEPTED_PEER_INVITATION = 1;
    const TYPE_SUGGESTED_PEER = 2;
    const TYPE_PEER_EMAIL = 3;
    const TYPE_POSTED_ANNOUNCEMENT = 4;
    const TYPE_POSTED_NEWS_ITEM = 5;
    const TYPE_POSTED_DISCUSSION_GROUP = 6;
    const TYPE_POSTED_DISCUSSION_TOPIC = 7;
    const TYPE_POSTED_DISCUSSION_POST = 8;
    const TYPE_POSTED_DISCUSSION_COMMENT = 9;
    const TYPE_SUBSCRIBED_DISCUSSION_PEER = 10;
    const TYPE_UNSUBSCRIBED_DISCUSSION_PEER = 11;
    const TYPE_PENDING_ASSINGMENT = 12;
    const TYPE_SUBMITTED_ASSIGNMENT = 13;
    const TYPE_SUBMITTED_ASSIGNMENT_FILE = 14;
    const TYPE_SUBMITTED_COURSE_FILE = 15;
    const TYPE_UPCOMING_ASSIGNMENT = 16;
    const TYPE_UPCOMING_EVENT = 17;
    const TYPE_RECEIVED_EMAIL = 18;

    static public $types = array(
        0 => 'Sent peer invitation',
        1 => 'Accepted peer invitation',
        2 => 'Suggested peer',
        3 => 'Sent email',
        4 => 'Posted announcenment',
        5 => 'Posted news',
        6 => 'Posted discussion group',
        7 => 'Posted discussion topic',
        8 => 'Posted discussion post',
        9 => 'Posted discussion comment',
        10 => 'Subscribed discussion peer',
        11 => 'Unsubscribed discussion peer',
        12 => 'Pending assignment',
        13 => 'Submitted assignment',
        14 => 'Submitted assignment file',
        15 => 'Submitted course file',
        16 => 'Upcoming assignment',
        17 => 'Upcoming event',
        18 => 'Received email'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object ActivityFeedTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ActivityFeed');
    }

    public function findByProfileId($profileId, $limit = null) {
        $q = Doctrine_Query::create()
            ->from('ActivityFeed af')
            ->innerJoin('af.ActivityFeedProfiles afu')
            ->andWhere('afu.profile_id = ?', $profileId);
        if ($limit) {
            $q->limit($limit);
        }

        $q->addOrderBy('af.created_at DESC');
        return $q->execute();
    }

    public function findByProfileIdAndType($profileId, $type, $limit = null) {
        $q = Doctrine_Query::create()
            ->from('ActivityFeed af')
            ->innerJoin('af.ActivityFeedProfiles afu')
            ->andWhere('afu.profile_id = ?', $profileId)
            ->andWhere('af.type = ?', $type);
        if ($limit) {
            $q->limit($limit);
        }

        $q->addOrderBy('af.created_at DESC');
        return $q->execute();
    }

}