<?php

/**
 * Announcement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Announcement extends BaseAnnouncement {

    public function postInsert($event) {
        // save this activity
        $activityFeed = new ActivityFeed();
        $activityFeed->setProfileId($this->getProfileId());
        $activityFeed->setItemId($this->getId());
        $activityFeed->setType(ActivityFeedTable::TYPE_ANNOUNCEMENT_POSTED);
        $activityFeed->save();

        // link this activity with the current profile
        $profileActivityFeed = new ProfileActivityFeed();
        $profileActivityFeed->setProfileId($this->getProfileId());
        $profileActivityFeed->setActivityFeedId($activityFeed->getId());
        $profileActivityFeed->save();
    }

    public function getToEmails() {
        $toEmails = "";
        foreach (ProfileTable::getInstance()->findAll() as $user) {
            $toEmails .= $user->getName() . " <" . $user->getEmail() . ">,";
        }

        $toEmails = trim($toEmails, ",");
        return $toEmails;
    }

}
