<?php

/**
 * Assignment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecollegeplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Assignment extends BaseAssignment
{
	/*public function getDueDate()
	{
		$this->getDateTimeObject()
		return parent::getDateTimeObject('due_date')->format('d/m/y');
	}
	
	public function getLockUntil()
	{
		return parent::getDateTimeObject('lock_until')->format('d/m/y');
	}
	
	public function getLockAfter()
	{
		return parent::getDateTimeObject('lock_after')->format('d/m/y');
	}*/

    public function getDisplaySubmission()
    {
        return AssignmentTable::$submission_types[parent::_get('submission')];
    }
}
