<?php

/**
 * AssignmentDiscussionGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignmentDiscussionGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssignmentDiscussionGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssignmentDiscussionGroup');
    }
}