<?php

/**
 * AssignmentGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignmentGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssignmentGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssignmentGroup');
    }
}