<?php

/**
 * AssignmentSubmissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignmentSubmissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssignmentSubmissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssignmentSubmission');
    }
}