<?php

/**
 * Attendance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attendance extends BaseAttendance
{

    public function getSummaryAttendance()
    {
        return "Take attendance"; //9:00am - 11:00am<br />T:12, P:26, E:2, A:8
    }

    public function getAttendanceSummary()
    {
        $statuses = StudentAttendanceTable::getInstance()->getStatuses();
        $total = StudentAttendanceTable::getInstance()->retrieveByAttendanceAndStatus($this->get("id"))->count();
        $summary = array();

        foreach ($statuses as $key => $status)
        {
            $status_total = StudentAttendanceTable::getInstance()->retrieveByAttendanceAndStatus($this->get("id"), $key)->count();

            $summary[] = array("status" => $status, "total" => $status_total, "percentage" => sprintf("%.1f", $status_total / $total * 100));
        }

        return $summary;
    }

}