<?php

/**
 * BulletinBoardTrashTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardTrashTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardTrashTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoardTrash');
    }

    public function findOneByBulletinBoardAndUserId($bulletin_board_post_id = null, $user_id = null)
    {
        $query = $this->createQuery('bbt')
            ->where('bbt.user_id = ?', $user_id)
            ->addWhere('bbt.bulletin_board_post_id = ?', $bulletin_board_post_id);

        return $query->fetchOne();
    }
}