<?php

/**
 * BulletinBoardPostAssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardPostAssignmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardPostAssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoardPostAssignment');
    }
}