<?php

/**
 * BulletinBoardPostUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardPostUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardPostUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoardPostUser');
    }
}