<?php

/**
 * BulletinBoardPostCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardPostCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardPostCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoardPostCourse');
    }
}