<?php

/**
 * BulletinBoardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardTable extends Doctrine_Table
{    
    static public $types = array(
        1 => 'Public',
        2 => 'Course',
        3 => 'Assignment',
    );

    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoard');
    }

    public function retrieveBulletinBoardsExceptTrashed($user_id, Doctrine_Query $q = null, $limit = 10)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('BulletinBoard bb');
        }
        $q->where('id NOT IN (SELECT bbt.bulletin_board_post_id FROM BulletinBoardTrash bbt WHERE bbt.user_id = ? AND bbt.bulletin_board_post_id = bb.id)', $user_id);

        $q->addOrderBy('bb.created_at DESC');
        $q->limit($limit);

        return $q->execute();
    }

    public function retrieveBulletinBoards($user_id, Doctrine_Query $q = null, $limit = 10)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('BulletinBoard bb');
        }
        $q->where('id NOT IN (SELECT bbt.bulletin_board_post_id FROM BulletinBoardTrash bbt WHERE bbt.user_id = ? AND bbt.bulletin_board_post_id = bb.id)', $user_id);

        $q->addOrderBy('bb.created_at DESC');
        $q->limit($limit);

        return $q->execute();
    }

}