<?php

/**
 * BulletinBoardPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinBoardPostTable extends Doctrine_Table
{
    static public $types = array(
        1 => 'Public',
        2 => 'Course',
        3 => 'Assignment',
    );

    /**
     * Returns an instance of this class.
     *
     * @return object BulletinBoardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinBoardPost');
    }

    public function retrieveBulletinBoardsExceptTrashed($user_id, Doctrine_Query $q = null, $limit = 10)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('BulletinBoardPost bbp');
        }
        $q->where('id NOT IN (SELECT bbpt.bulletin_board_post_id FROM BulletinBoardTrash bbpt WHERE bbpt.user_id = ? AND bbpt.bulletin_board_post_id = bbp.id)', $user_id);

        $q->addOrderBy('bbp.created_at DESC');
        $q->limit($limit);

        return $q->execute();
    }

    public function retrieveBulletinBoards($user_id, Doctrine_Query $q = null, $limit = 10)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('BulletinBoardPost bbp');
        }
        $q->where('id NOT IN (SELECT bbpt.bulletin_board_post_id FROM BulletinBoardTrash bbpt WHERE bbpt.user_id = ? AND bbpt.bulletin_board_post_id = bbp.id)', $user_id);

        $q->addOrderBy('bbp.created_at DESC');
        $q->limit($limit);

        return $q->execute();
    }
}