<?php

/**
 * CalendarEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarEventTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object CalendarEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CalendarEvent');
    }

    public function retrieveByProfileIdAndVisibility($profile_id = null, $calendar_ids = array(), $is_public = true)
    {
        if (count($calendar_ids) == 0)
            return array();

        $query = $this->createQuery('ce')
            ->select("ce.id, ce.name AS title, ce.from_date AS start, ce.to_date AS end, c.color AS backgroundColor, c.color AS borderColor")
            ->innerJoin('ce.Calendar c')
            ->innerJoin('c.Owner o')
            ->where('(o.owner_id = ? OR c.is_public = ?)', array($profile_id, $is_public))
            ->andWhereIn('c.id', $calendar_ids)
            ->orderBy('ce.from_date, ce.to_date DESC');

        return $query->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

    public function retrieveByVisibility($is_public = true)
    {
        $query = $this->createQuery('ce')
            ->select("ce.id, ce.name AS title, ce.from_date AS start, ce.to_date AS end, c.color AS backgroundColor, c.color AS borderColor")
            ->innerJoin('ce.Calendar c')
            ->innerJoin('c.Owner o')
            ->where('(c.is_public = ?)', $is_public)
            ->orderBy('ce.from_date, ce.to_date DESC');

        return $query->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

}