<?php

/**
 * CalendarEventAttendeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarEventAttendeeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CalendarEventAttendeeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('CalendarEventAttendee');
    }

    public function deleteByEventIdsAndUserId($eventIds, $userId) {
        $query = $this->createQuery()
                ->delete()
                ->whereIn('calendar_event_id', $eventIds)
                ->andWhere("user_id = ?", $userId);

        return $query->execute();
    }

    public function deleteByEventIdAndUserIds($eventId, $userIds = array()) {
        $query = $this->createQuery()
                ->delete()
                ->whereIn('user_id', $userIds)
                ->andWhere("calendar_event_id = ?", $eventId);

        return $query->execute();
    }

}