<?php

/**
 * CalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarTable extends Doctrine_Table
{
    static public $types = array(
        1 => 'Personal Calendar',
        2 => 'Public Calendar',
        3 => 'Academic Calendar',
        4 => 'Social Calendar',
        5 => 'Exams Calendar'
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object CalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Calendar');
    }

    public function getTypes()
    {
        return self::$types;
    }
    
    public function retrieveByProfileIdAndVisibility($profile_id = null, $is_public = true)
    {
        $query = $this->createQuery('c')
            ->select("c.id, c.name, c.color");

        return $this->getByProfileIdAndVisibilityQuery($query, $profile_id, $is_public)->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }
    
    public function retrieveByIdsProfileIdAndVisibility($profile_id = null, $is_public = true)
    {
        $query = $this->createQuery('c')
            ->select("c.id");

        return $this->getByProfileIdAndVisibilityQuery($query, $profile_id, $is_public)->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }
    
    public function getByProfileIdAndVisibilityQuery(Doctrine_Query $query, $profile_id, $is_public)
    {
      return $query->innerJoin('c.Owner o')
            ->where('o.owner_id = ?', $profile_id)
            ->orWhere('c.is_public = ?', $is_public);
    }
}