<?php

/**
 * CalendarEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CalendarEvent extends BaseCalendarEvent
{
    function getWhen()
    {
        return $this->getDateTimeObject('from_date')->format('d/m/Y') . " - " . $this->getDateTimeObject('to_date')->format('d/m/Y');
    }
}
