<?php

/**
 * CalendarEventAttendeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarEventAttendeeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CalendarEventAttendeeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('CalendarEventAttendee');
    }

    public function deleteByEventIdsAndProfileId($eventIds, $profileId) {
        $query = $this->createQuery()
                ->delete()
                ->whereIn('calendar_event_id', $eventIds)
                ->andWhere("profile_id = ?", $profileId);

        return $query->execute();
    }

    public function deleteByEventIdAndProfileIds($eventId, $profileIds = array()) {
        $query = $this->createQuery()
                ->delete()
                ->whereIn('profile_id', $profileIds)
                ->andWhere("calendar_event_id = ?", $eventId);

        return $query->execute();
    }

}