<?php

/**
 * CampusCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampusCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampusCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CampusCourse');
    }
}