<?php

/**
 * ContactStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactStudentTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactStudent');
    }
}