<?php

/**
 * ContactInstructorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactInstructorTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactInstructorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactInstructor');
    }
}