<?php

/**
 * ContactStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactStaffTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactStaff');
    }
}