<?php

/**
 * Correspondence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Correspondence extends BasesfGuardGroup
{

    public function setDeterminedType($innitiator_type = 'Student')
    {
        $correspondent_type = ProfileTable::getInstance()->determineUserTypeByUserId($this->get('correspondent_id'));
        $correspondence_types = CorrespondenceTable::getInstance()->getTypes();
        
        $flipped_correspondence_types = array_flip($correspondence_types);
        
        $type = $innitiator_type." ".$correspondent_type;
        
        $this->setType($flipped_correspondence_types[$type]);
    }

    public function getRelevantUser($user_id)
    {
        return (parent::getCorrespondentId() == $user_id) ? parent::getInnitiator() : parent::getCorrespondent();
    }

}
