<?php

/**
 * CourseFaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseFaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseFaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseFaq');
    }
}