<?php

/**
 * CourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseTable extends Doctrine_Table {

  const MODULE_STUDENT = "student";
  const MODULE_INSTRUCTOR = "instructor";
  const MODULE_STAFF = "staff";
  const MODULE_MAILING_LIST = "mailing_list";

  /**
   * Returns an instance of this class.
   *
   * @return object CourseTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Course');
  }

  public function findByPeerId($profileId, $limit = null) {
    $q = $this->createQuery('c')
        ->innerJoin('c.CourseProfiles cp')
        ->addWhere('cp.profile_id = ?', $profileId);

    if ($limit) {
      $q->limit($limit);
    }
    return $q->execute();
  }

}