<?php

/**
 * CourseActivityFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseActivityFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseActivityFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseActivityFeed');
    }
}