<?php

/**
 * CourseSyllabusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseSyllabusTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CourseSyllabusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseSyllabus');
    }

    public function findOrCreateOneByCourse($courseId)
    {
        if (!is_object($courseSyllabus = self::getInstance()->findOneByCourseId($courseId))) {
            // save a course syllabus object
            $courseSyllabus = new CourseSyllabus();
            $courseSyllabus->setCourseId($courseId);
            $courseSyllabus->setContent("Edit me");
            $courseSyllabus->save();
        }
        return $courseSyllabus;
    }

}