<?php

/**
 * CourseMeetingTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseMeetingTimeTable extends Doctrine_Table
{
    public static $days = array(
        1 => 'Monday',
        2 => 'Tuesday',
        3 => 'Wednesday',
        4 => 'Thursday',
        5 => 'Friday',
        6 => 'Saturday',
        7 => 'Sunday',
    );

    /**
     * Returns an instance of this class.
     *
     * @return object CourseMeetingTimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseMeetingTime');
    }

    public function getDays()
    {
        return self::$days;
    }

    public function getDayValues()
    {
        return array_keys(self::$days);
    }

    public function getTimes()
    {
        $times = array();
        for($t = 0; $t < 24; $t++)
        {
            $meridiem = "AM";
            if($t >= 12)
            {
                $meridiem = "PM";
            }
            $times[str_pad($t, 2, "0", STR_PAD_LEFT).":00".$meridiem] = str_pad($t, 2, "0", STR_PAD_LEFT).":00".$meridiem;
            $times[str_pad($t, 2, "0", STR_PAD_LEFT).":15".$meridiem] = str_pad($t, 2, "0", STR_PAD_LEFT).":15".$meridiem;
            $times[str_pad($t, 2, "0", STR_PAD_LEFT).":30".$meridiem] = str_pad($t, 2, "0", STR_PAD_LEFT).":30".$meridiem;
            $times[str_pad($t, 2, "0", STR_PAD_LEFT).":45".$meridiem] = str_pad($t, 2, "0", STR_PAD_LEFT).":45".$meridiem;
        }
        return $times;
    }

    public function getTimesValues()
    {
        return $this->getTimes();
    }

    public function findByCourse($course_id)
    {
        $q = $this->createQuery('c')
            ->where('c.course_id = ?', $course_id)
            ->orderBy('c.day ASC');
        return $q->execute();
    }

}