<?php

/**
 * CourseFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseFile');
    }
}