<?php

/**
 * CourseDiscussionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseDiscussionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseDiscussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseDiscussion');
    }
}