<?php

/**
 * CourseLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseLinkTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object CourseLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseLink');
    }

    public function findByCourse($course_id)
    {
        return $this->createQuery('cl')
            ->where('cl.course_id = ?', $course_id)
            ->orderBy('cl.name, cl.url ASC')
            ->execute();
    }

}