<?php

/**
 * Course
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Course extends BaseCourse {

    public function getAnnouncements() {
        return Doctrine_Core::getTable('Announcement')->findByCourseId($this->getId());
    }

    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);

        if (!$this->isNew()) {
            $gradebook = new Gradebook();
            $gradebook->setCourseId($this->get("id"));
            $gradebook->setItems(0);
            $gradebook->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(75);
            $gradebookScale->setMaxPoints(100);
            $gradebookScale->setCode("A");
            $gradebookScale->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(65);
            $gradebookScale->setMaxPoints(74);
            $gradebookScale->setCode("B");
            $gradebookScale->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(55);
            $gradebookScale->setMaxPoints(64);
            $gradebookScale->setCode("C");
            $gradebookScale->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(45);
            $gradebookScale->setMaxPoints(54);
            $gradebookScale->setCode("D");
            $gradebookScale->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(35);
            $gradebookScale->setMaxPoints(44);
            $gradebookScale->setCode("E");
            $gradebookScale->save();

            $gradebookScale = new GradebookScale();
            $gradebookScale->setGradebookId($gradebook->get("id"));
            $gradebookScale->setMinPoints(0);
            $gradebookScale->setMaxPoints(34);
            $gradebookScale->setCode("F");
            $gradebookScale->save();
        }
    }

    public function retrieveUpcomingAssignments() {
        $q = Doctrine_Query::create()
                ->from('Assignment a')
                ->addWhere("a.course_id = ?", $this->get("id"))
                ->addWhere('a.due_date > ?', date('d-m-y H:i:s', strtotime("NOW")))
                ->limit(1);

        return AssignmentTable::getInstance()->retrieveUpcomingAssignments($q);
    }

    public function getDiscussionGroup() {
        $courseDiscussionGroup = CourseDiscussionGroupTable::getInstance()->findOneByCourseId($this->getId());
        if (is_object($courseDiscussionGroup)) {
            return $courseDiscussionGroup->getDiscussionGroup();
        }
        return null;
    }
}
