<?php

/**
 * CourseDiscussionGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseDiscussionGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseDiscussionGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseDiscussionGroup');
    }

    public function findOneByCourseIdAndParentFolderId($courseId, $parentFolderId)
    {
        $query = $this->createQuery('cf')
            ->addWhere('cf.course_id = ?', $courseId)
            ->innerJoin('cf.Folder f')
            ->andWhere('f.parent_id = ?', $parentFolderId);

        return $query->fetchOne();
    }
}