<?php

/**
 * CourseFolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseFolderTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object CourseFolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseFolder');
    }

    public function findOrCreateByCoursesAndParentFolder($courses, $parentFolder)
    {
        foreach ($courses as $course)
        {
            if (!is_object($courserFolder = $this->getInstance()->findOneByCourseIdAndParentFolderId($course['id'], $parentFolder->getId())))
            {
                // save the course folder
                $folder = new Folder();
                $folder->setName($course['code']);
                $folder->setParentId($parentFolder->getId());
                $folder->getNode()->insertAsLastChildOf($parentFolder);

                // save the course folder linking
                $courserFolder = new CourseFolder();
                $courserFolder->setCourseId($course['id']);
                $courserFolder->setFolderId($folder->getId());
                $courserFolder->save(); 
            }
        }
    }

    public function findOneByCourseIdAndParentFolderId($courseId, $parentFolderId)
    {
        $query = $this->createQuery('cf')
            ->addWhere('cf.course_id = ?', $courseId)
            ->innerJoin('cf.Folder f')
            ->andWhere('f.parent_id = ?', $parentFolderId);

        return $query->fetchOne();
    }

}