<?php

/**
 * CourseAnnouncementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseAnnouncementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseAnnouncementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseAnnouncement');
    }
}