<?php

/**
 * CourseMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseMailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseMailingList');
    }
}