<?php

/**
 * CourseReadingItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseReadingItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseReadingItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseReadingItem');
    }

    public function findByCourse($course_id)
    {
        return $this->createQuery('cri')
            ->where('cri.course_id = ?', $course_id)
            ->orderBy('cri.author, cri.title ASC')
            ->execute();
    }
}