<?php

/**
 * DiscussionPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus.org
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionPost extends BaseDiscussionPost
{

    public function postInsert($event) {
        // save this activity
        $replacements = array(
            $this->getProfile()->getName(),
            $this->getProfile()->getSlug(),
            $this->getDiscussionTopic()->getSlug(),
            $this->getDiscussionTopic()->getSubject(),
            $this->getMessage(),
        );

        $activityTemplate = ActivityTemplateTable::getInstance()->findOneByType(ActivityTemplateTable::TYPE_POSTED_DISCUSSION_MESSAGE);

        if ($activityTemplate) {
            $activityFeed = new ActivityFeed();
            $activityFeed->setActivityTemplate($activityTemplate);
            $activityFeed->setReplacements(json_encode($replacements));
            $activityFeed->setProfileId($this->getProfileId());
            $activityFeed->setItemId($this->getId());
            $activityFeed->save();

            // link this activity with the current discussion users
            foreach ($this->getDiscussionTopic()->getDiscussion()->getMembers() as $discussionMemberPeer) {
                $profileActivityFeed = new ProfileActivityFeed();
                $profileActivityFeed->setProfileId($discussionMemberPeer->getProfileId());
                $profileActivityFeed->setActivityFeedId($activityFeed->getId());
                $profileActivityFeed->save();
            }
        }
    }
}
