<?php

/**
 * DiscussionCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionComment');
    }

    public function retrieveReplies(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('DiscussionComment dc');
        }
        $q->addOrderBy('dc.created_at DESC');
        return $q->execute();
    }

    public function getNbNewReplies($courseId = null)
    {
        $q = $this->createQuery('dc')
            ->innerJoin('dc.DiscussionPost dp')
            ->innerJoin('dp.DiscussionTopic dt')
            ->innerJoin('dt.DiscussionGroup dg');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussionGroup cdg')
                ->addWhere('cdg.course_id = ?', $courseId);
        }
        $q->addWhere('dc.created_at > ?', date('Y-m-d H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }
}