<?php

/**
 * DiscussionTopicMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTopicMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTopicMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionTopicMessage');
    }

    public function retrieveMessages(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('DiscussionTopicMessage dtm');
        }
        $q->addOrderBy('dtm.created_at DESC');
        return $q->execute();
    }

    public function getNbNewMessages($courseId = null)
    {
        $q = $this->createQuery('dtm')
            ->innerJoin('dtm.DiscussionTopic dt')
            ->innerJoin('dt.Discussion d');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussion cd')
                ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->addWhere('dtm.created_at > ?', date('d-m-y H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }
}