<?php

/**
 * DiscussionTopicMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecollegeplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionTopicMessage extends BaseDiscussionTopicMessage
{

    public function postSave($event)
    {        
        // save this activity
        $replacements = array($this->getDiscussionTopic()->getId(), myToolkit::shortenString($this->getMessage()));
        $activityTemplate = ActivityTemplateTable::getInstance()->findOneByType(ActivityTemplateTable::TYPE_POSTED_DISCUSSION_MESSAGE);

        if ($activityTemplate)
        {
            $activityFeed = new ActivityFeed();
            $activityFeed->setActivityTemplate($activityTemplate);
            $activityFeed->setReplacements(json_encode($replacements));
            $activityFeed->save();
        }
    }
}
