<?php

/**
 * DiscussionPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionPost');
    }

    public function retrievePosts(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('DiscussionPost dtm');
        }
        $q->addOrderBy('dtm.created_at DESC');
        return $q->execute();
    }

    public function getNbNewMessages($courseId = null)
    {
        $q = $this->createQuery('dtm')
            ->innerJoin('dtm.DiscussionTopic dt')
            ->innerJoin('dt.Discussion d');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussion cd')
                ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->addWhere('dtm.created_at > ?', date('Y-m-d H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }
}