<?php

/**
 * DiscussionActivityFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionActivityFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionActivityFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionActivityFeed');
    }
}