<?php

/**
 * DiscussionComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus.org
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionComment extends BaseDiscussionComment
{

    public function updateCounts() {
        $this->getDiscussionPost()->getDiscussionTopic()->setNbReplies($this->getDiscussionPost()->getDiscussionTopic()->getNbReplies() + 1);
        $this->getDiscussionPost()->getDiscussionTopic()->setLatestTopicReplyId($this->getId());
        $this->getDiscussionPost()->getDiscussionTopic()->setUpdatedAt($this->getCreatedAt());
        $this->getDiscussionPost()->getDiscussionTopic()->save();

        $this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->setNbReplies($this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->getNbReplies() + 1);
        $this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->setNbTopics($this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->getNbTopics() + 1);
        $this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->setLatestTopicReplyId($this->getId());
        $this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->setUpdatedAt($this->getCreatedAt());
        $this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->save();
    }

    public function postInsert($event) {
        // update counts
        $this->updateCounts();

        // save this activity
        $replacements = array(
            $this->getProfile()->getSlug(),
            $this->getProfile()->getName(),
            $this->getDiscussionPost()->getDiscussionTopic()->getSlug(),
            myToolkit::shortenString($this->getDiscussionPost()->getDiscussionTopic()->getSubject(), 50),
            myToolkit::shortenString($this->getReply(), 50)
        );

        // find the activity template for this logging
        $activityTemplate = ActivityTemplateTable::getInstance()->findOneByType(ActivityTemplateTable::TYPE_POSTED_DISCUSSION_REPLY);

        if ($activityTemplate) {
            $activityFeed = new ActivityFeed();
            $activityFeed->setActivityTemplate($activityTemplate);
            $activityFeed->setReplacements(json_encode($replacements));
            $activityFeed->setProfileId($this->getProfileId());
            $activityFeed->setItemId($this->getId());
            $activityFeed->save();

            // link this activity with the current discussion users
            foreach ($this->getDiscussionPost()->getDiscussionTopic()->getDiscussion()->getMembers() as $discussionMemberPeer) {
                $profileActivityFeed = new ProfileActivityFeed();
                $profileActivityFeed->setProfileId($discussionMemberPeer->getProfileId());
                $profileActivityFeed->setActivityFeedId($activityFeed->getId());
                $profileActivityFeed->save();
            }
        }
    }
}
