<?php

/**
 * DiscussionTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTopicTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTopicTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DiscussionTopic');
    }

    public function getNbNewTopics($courseId = null) {
        $q = $this->createQuery('dt')
                ->innerJoin('dt.Discussion d');
        if ($courseId) {
            $q->innerJoin('d.CourseDiscussion cd')
                    ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->addWhere('dt.created_at > ?', date('d-m-y H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }

    public function getTopicWithRecentActivity($courseId = null) {
        $q = $this->createQuery('dt')
                ->innerJoin('dt.Discussion d')
                ->leftJoin('dt.Messages dtm')
                ->leftJoin('dtm.Replies dtms');
        if ($courseId) {
            $q->innerJoin('d.CourseDiscussion cd')
                    ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->orderBy('dtms.id DESC')
                ->orderBy('dtm.id DESC')
                ->orderBy('dt.id DESC');

        return $q->fetchOne();
    }

    public function getTopicWithMostActivities($courseId = null) {
        $q = $this->createQuery('dt')
                ->innerJoin('dt.Discussion d')
                ->leftJoin('dt.Messages dtm')
                ->leftJoin('dtm.Replies dtms');
        if ($courseId) {
            $q->innerJoin('d.CourseDiscussion cd')
                    ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->orderBy('dtms.id DESC')
                ->orderBy('dtm.id DESC')
                ->orderBy('dt.id DESC');

        return $q->fetchOne();
    }

    public function findOrCreateOneByUserId($userId, $discussionId) {
        $discussionTopic = self::getInstance()->findOneByUserId($userId);
        if (!is_object($discussionTopic)) {
            $discussionTopic = new DiscussionTopic();
            $discussionTopic->setSubject("Welcome message from the TutorPlus team!");
            $discussionTopic->setMessage("Hi fellow participants, It's a great pleasure to be part of this collaborative learning platform and be readily available to share relevant academic experiences we all have to endure in our varied normal discources. I hope we will all exhibit the same sincereness and sense of belonging in enganging with the learning materials and our peers. God bless!");
            $discussionTopic->setDiscussionId($discussionId);
            $discussionTopic->setUserId($userId);
            $discussionTopic->save();
        }
        return $discussionTopic;
    }

    public function findOneByUserId($userId) {
        $q = $this->createQuery('dt')
                ->innerJoin('dt.Discussion d');

        $q->addWhere('d.user_id = ?', $userId);
        $q->addWhere('d.is_primary = ?', true);
        return $q->fetchOne();
    }

}