<?php

/**
 * DiscussionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTypeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DiscussionType');
    }

}