<?php

/**
 * DiscussionTopicTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTopicTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTopicTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionTopicType');
    }
}