<?php

/**
 * DiscussionMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionMember extends BaseDiscussionMember
{

    function getSubscriptionTypeDisplay()
    {
        $subscription_type = "";

        if (isset(DiscussionMemberTable::$subscription_types[parent::_get("subscription_type")]))
        {
            $subscription_type = DiscussionMemberTable::$subscription_types[parent::_get("subscription_type")];
        }
        if (is_array($subscription_type = explode(" - ", $subscription_type)))
        {
            return $subscription_type[0];
        }
        else
        {
            return $subscription_type;
        }
    }

    function getMembershipTypeDisplay()
    {
        $membership_type = "";

        if (isset(DiscussionMemberTable::$membership_types[parent::_get("membership_type")]))
        {
            $membership_type = DiscussionMemberTable::$membership_types[parent::_get("membership_type")];
        }
        if (is_array($membership_type = explode(" - ", $membership_type)))
        {
            return $membership_type[0];
        }
        else
        {
            return $membership_type;
        }
    }

    function getPostingPermissionTypeDisplay()
    {
        $posting_permission_type = "";

        if (isset(DiscussionMemberTable::$posting_permission_types[parent::_get("posting_permission_type")]))
        {
            $posting_permission_type = DiscussionMemberTable::$posting_permission_types[parent::_get("posting_permission_type")];
        }
        if (is_array($posting_permission_type = explode(" - ", $posting_permission_type)))
        {
            return $posting_permission_type[0];
        }
        else
        {
            return $posting_permission_type;
        }
    }

    function getStatusDisplay()
    {
        $status = "";

        if (isset(DiscussionMemberTable::$statues[parent::_get("status")]))
        {
            $status = DiscussionMemberTable::$statues[parent::_get("status")];
        }
        if (is_array($status = explode(" - ", $status)))
        {
            return $status[0];
        }
        else
        {
            return $status;
        }
    }
}
