<?php

/**
 * DiscussionTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTopicTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionTopic');
    }

    public function getNbNewTopics($courseId = null)
    {
        $q = $this->createQuery('dt')
            ->innerJoin('dt.Discussion d');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussion cd')
                ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->addWhere('dt.created_at > ?', date('d-m-y H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }

    public function getTopicWithRecentActivity($courseId = null)
    {
        $q = $this->createQuery('dt')
            ->innerJoin('dt.Discussion d')
            ->leftJoin('dt.Messages dtm')
            ->leftJoin('dtm.Replies dtms');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussion cd')
                ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->orderBy('dtms.id DESC')
            ->orderBy('dtm.id DESC')
            ->orderBy('dt.id DESC');

        return $q->fetchOne();
    }

}