<?php

/**
 * DiscussionTopicReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionTopicReplyTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTopicReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionTopicReply');
    }

    public function retrieveReplies(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('DiscussionTopicReply dtr');
        }
        $q->addOrderBy('dtr.created_at DESC');
        return $q->execute();
    }

    public function getNbNewReplies($courseId = null)
    {
        $q = $this->createQuery('dtr')
            ->innerJoin('dtr.DiscussionTopicMessage dtm')
            ->innerJoin('dtm.DiscussionTopic dt')
            ->innerJoin('dt.Discussion d');
        if ($courseId)
        {
            $q->innerJoin('d.CourseDiscussion cd')
                ->addWhere('cd.course_id = ?', $courseId);
        }
        $q->addWhere('dtr.created_at > ?', date('d-m-y H:i:s', strtotime("NOW - 7 days")));
        return $q->execute();
    }

}