<?php

/**
 * DiscussionComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus.org
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionComment extends BaseDiscussionComment {

    public function postInsert($event) {
        // update statistics
        $discussionTopic = $this->getDiscussionPost()->getDiscussionTopic();
        $discussionTopic->setCommentCount($discussionTopic->getCommentCount() + 1);
        $discussionTopic->setLatestCommentId($this->getId());
        $discussionTopic->setUpdatedAt($this->getCreatedAt());
        $discussionTopic->save();

        $discussion = $discussionTopic->getDiscussion();
        $discussion->setCommentCount($discussion->getCommentCount() + 1);
        $discussion->setLatestCommentId($this->getId());
        $discussion->setUpdatedAt($this->getCreatedAt());
        $discussion->save();

        // save this activity
        $activityFeed = new ActivityFeed();
        $activityFeed->setProfileId($this->getProfileId());
        $activityFeed->setItemId($this->getId());
        $activityFeed->setType(ActivityFeedTable::TYPE_POSTED_DISCUSSION_COMMENT);
        $activityFeed->save();

        // link this activity with the current profile
        $profileActivityFeed = new ProfileActivityFeed();
        $profileActivityFeed->setProfileId($this->getProfileId());
        $profileActivityFeed->setActivityFeedId($activityFeed->getId());
        $profileActivityFeed->save();
    }

}
