<?php

/**
 * EmailMessageReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailMessageReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailMessageReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailMessageReply');
    }
}