<?php

/**
 * EmailTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailTemplate');
    }
}