<?php

/**
 * EmailMessageCorrespondenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailMessageCorrespondenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailMessageCorrespondenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailMessageCorrespondence');
    }
}