<?php

/**
 * FileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileTable extends Doctrine_Table
{
    static public $mimeTypes = array(
        'text/plain',
        'application/msword',
        'application/pdf',
        'application/vnd.ms-excel',
        'application/vnd.ms-powerpoint',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.oasis.opendocument.text-template',
        'application/vnd.oasis.opendocument.text-web',
        'application/vnd.oasis.opendocument.text-master',
        'application/vnd.oasis.opendocument.graphics',
        'application/vnd.oasis.opendocument.graphics-template',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.presentation-template',
        'application/vnd.oasis.opendocument.spreadsheet',
        'application/vnd.oasis.opendocument.spreadsheet-template',
        'application/vnd.oasis.opendocument.chart',
        'application/vnd.oasis.opendocument.formula',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/x-msexcel',
        'application/x-msword',
        'application/zip');

    /**
     * Returns an instance of this class.
     *
     * @return object FileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('File');
    }

    public function findByCourse($course_id)
    {
        return $this->createQuery('f')
//            ->where('f.course_id = ?', $course_id)
//            ->orderBy('cri.author, cri.title ASC')
            ->execute();
    }

    public function fetchByFolderId($folder_id = null)
    {
        return $this->createQuery('f')
            ->addWhere('f.folder_id = ?', $folder_id)
            ->orderBy('f.created_at DESC')
            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

}