<?php

/**
 * File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class File extends BaseFile
{

    public function postSave($event)
    {
        $user = sfContext::getInstance()->getUser();
        $folderSection = $user->getMyAttribute('folder_section', FolderTable::DOCUMENTS_SECTION);
        if ($folderSection == FolderTable::COURSES_SECTION)
        {
            $courseId = $user->getMyAttribute('course_show_id', null);            
            $course = CourseTable::getInstance()->find($courseId);
            $replacements = array($course->getCode(), $courseId);
            $activityTemplate = ActivityTemplateTable::getInstance()->findOneByType(ActivityTemplateTable::TYPE_SUBMITTED_COURSE_FILE);

            if ($activityTemplate)
            {
                $activityFeed = new ActivityFeed();
                $activityFeed->setActivityTemplate($activityTemplate);
                $activityFeed->setReplacements(json_encode($replacements));
                $activityFeed->save();
            }
        }
    }

}
