<?php

/**
 * Folder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecollegeplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Folder extends BaseFolder
{

    /**
     * Returns an array of the descendants Folder objects indexed
     *
     * @return array
     */
    public function getDescendants()
    {
        $folders = FolderTable::getInstance()
            ->createQuery('f')
            ->orderBy('f.lft ASC')
            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);

        $descendants = $this->getFolderDescendentsById($folders[0], 14);

        $file_system = "<ul id=\"browser\" class=\"filetree\">";
        foreach ($descendants as $descendant)
        {
            $css_class = "class=\"closed directory expandable\"";
            if ($descendant['__children'])
            {
                $file_system .= "<li " . $css_class . "><span class=\"listing_parent_id\">" . $descendant['id'] . "</span><span class=\"directory\">" . $descendant['name'] . "</span>";
                $file_system = $this->recurciveListing($file_system, $descendant);
                $file_system .= "</li>";
            }
            else
            {
                $file_system .= "<li " . $css_class . "><span class=\"listing_parent_id\">" . $descendant['id'] . "</span><span class=\"directory\">" . $descendant['name'] . "</span></li>";
            }
        }

        $file_system .= "</ul>";
        return $file_system;
    }

    private function getFolderDescendentsById($folder, $folder_id, $descendants = array())
    {
        if (isset($folder["__children"]) && count($folder["__children"]) > 0)
        {
            foreach ($folder["__children"] as $folder_local)
            {
                if ($folder_local['id'] == $folder_id)
                {
                    $descendants = $folder_local["__children"];
                }
                else
                {
                    $descendants = $this->getFolderDescendentsById($folder_local, $folder_id, $descendants);
                }
            }
        }
        return $descendants;
    }

    private function recurciveListing($file_system, $document)
    {
        if (count($document["__children"]) > 0)
        {
            $file_system .= "<ul>";
            foreach ($document["__children"] as $document_local)
            {
                $css_class = "class=\"closed directory expandable\"";
                if (isset($document_local["__children"]))
                {
                    $file_system .= "<li " . $css_class . "><span class=\"listing_parent_id\">" . $document_local['id'] . "</span><span class=\"directory\">" . $document_local['name'] . "</span>";
                    $file_system = $this->recurciveListing($file_system, $document_local);
                    $file_system .= "</li>";
                }
                else
                {
                    $file_system .= "<li " . $css_class . "><span class=\"listing_parent_id\">" . $document_local['id'] . "</span><span class=\"directory\">" . $document_local['name'] . "</span></li>";
                }
            }
            $file_system .= "</ul>";
        }
        return $file_system;
    }

}
