<?php

/**
 * Gradebook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecollegeplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Gradebook extends BaseGradebook
{

    public function calculateFinalGradeByStudent($studentId = null)
    {
        $finalGrade = 0;

        $studentGradebookItems = StudentGradebookItemTable::getInstance()->retrieveByStudentAndGradebook($studentId, $this->get('id'));

        foreach ($studentGradebookItems as $studentGradebookItem)
        {
            $finalGrade += $studentGradebookItem->getPoints() / 100 * $studentGradebookItem->getGradebookItem()->getWeight();
        }

        return sprintf("%.2f", $finalGrade);
    }

    public function calculateFinalGradeScaleByStudent($studentId = null)
    {
        $finalGrade = $this->calculateFinalGradeByStudent($studentId);

        foreach ($this->getGradebookScales() as $gradebookScale)
        {
            $finalGradeScaleId = $gradebookScale->getId();
            if($finalGrade >= $gradebookScale->getMinPoints() && $finalGrade <= $gradebookScale->getMaxPoints())
            {
                return $gradebookScale->getId();
            }
        }

        return $finalGradeScaleId;
    }

}
