<?php

/**
 * GradebookItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GradebookItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GradebookItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GradebookItem');
    }

    public function retrieveByGradebook($gradebook_id = null)
    {
        $query = $this->createQuery('gi')
            ->where('gi.gradebook_id = ?', $gradebook_id);

        return $query->execute();
    }
}