<?php

/**
 * GradebookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GradebookTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object GradebookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gradebook');
    }

    public function findOrCreateOneBy($column = null, $colum_value = null)
    {
        if (!is_object($gradebook = $this->getInstance()->findOneBy($column, $colum_value)))
        {
            $gradebook = new Gradebook();
            $gradebook->setCourseId($colum_value);
            $gradebook->setItems(0);
            $gradebook->save();
        }
        return $gradebook;
    }

}