<?php

/**
 * InstructorContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstructorContactTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstructorContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstructorContact');
    }
}