<?php

/**
 * InstructorMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstructorMailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstructorMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstructorMailingList');
    }

    public function deleteByInstructorIdsAndMailingListsId($instructorIds, $mailingListId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('instructor_id', $instructorIds)
            ->andWhere("mailing_list_id = ?", $mailingListId);

        return $query->execute();
    }

    public function deleteByMailingListIdsAndInstructorId($mailingListIds, $instructorId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('mailing_list_id', $mailingListIds)
            ->andWhere('instructor_id = ?', $instructorId);

        return $query->execute();
    }    
}