<?php

/**
 * InstructorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstructorTable extends ProfileTable
{
    static public $employment_types = array(
        0 => 'Full time',
        1 => 'Part time'
    );

    public function getEmploymentTypes()
    {
        return self::$employment_types;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object InstructorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Instructor');
    }

    public function retrieveByIds($ids = array())
    {
        if (count($ids) == 0)
        {
            return array();
        }
        $query = $this->createQuery('i')
            ->whereIn('i.id', $ids);

        return $query->execute();
    }

}