<?php

/**
 * MailingListCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingListCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingListCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingListCourse');
    }
}