<?php

/**
 * MailingListEmailMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingListEmailMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingListEmailMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingListEmailMessage');
    }
}