<?php

/**
 * MailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingListTable extends Doctrine_Table
{
    const MODULE_STUDENT = "student";
    const MODULE_INSTRUCTOR = "instructor";
    const MODULE_STAFF = "staff";

    /**
     * Returns an instance of this class.
     *
     * @return object MailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingList');
    }

    public function retrieveByIds($ids = array())
    {
        if (count($ids) == 0)
        {
            return array();
        }
        $query = $this->createQuery('ml')
            ->whereIn('ml.id', $ids);

        return $query->execute();
    }

}