<?php

/**
 * PaymentSchemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentSchemeTable extends Doctrine_Table {

    const FREQUENCY_MONTHLY = 0;
    const FREQUENCY_BI_ANNUALLY = 1;
    const FREQUENCY_ANNUALLY = 2;

    static public $frequencies = array(
        self::FREQUENCY_MONTHLY => 'Monthly',
        self::FREQUENCY_BI_ANNUALLY => 'Bi-annually',
        self::FREQUENCY_ANNUALLY => 'Annusally'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object PaymentSchemeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PaymentScheme');
    }

    public function getFrequencies() {
        return self::$frequencies;
    }

}