<?php

/**
 * PeerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peer');
    }
}