<?php

/**
 * ProfileBookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileBookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileBookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileBook');
    }
}