<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tutorplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
    public function isStudent()
    {
        return is_object(StudentTable::getInstance()->findOneBy("user_id", $this->getUserId()));
    }

    public function isInstructor()
    {
        return is_object(InstructorTable::getInstance()->findOneBy("user_id", $this->getUserId()));
    }

    public function isStaff()
    {
        return is_object(StaffTable::getInstance()->findOneBy("user_id", $this->getUserId()));
    }
    
    public function getStudent()
    {
        return StudentTable::getInstance()->findOneBy("user_id", $this->getUserId());
    }

    public function getInstructor()
    {
        return is_object(InstructorTable::getInstance()->findOneBy("user_id", $this->getUserId()));
    }

    public function getStaff()
    {
        return StaffTable::getInstance()->findOneBy("user_id", $this->getUserId());
    }

}
