<?php

/**
 * ProfileRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileRememberKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileRememberKey');
    }
}