<?php

/**
 * ProfileForgotPasswordTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileForgotPasswordTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object ProfileForgotPasswordTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('ProfileForgotPassword');
	}
	
	/**
	 * Delete records for a given profile
	 *
	 * @param int $profileId
	 *
	 * @return void
	 */
	public function deleteByProfileId($profileId)
	{
		$this->createQuery('pfp')
		->delete()
		->where('pfp.profile_id = ?', $profileId)
		->execute();
	}
}