<?php

/**
 * ProfileQualificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileQualificationTable extends Doctrine_Table
{ 
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileQualification');
    }

    public function getYears()
    {
        $start_year = date("Y", strtotime("- 70 years"));
        $end_year = date("Y");
        
        return range($start_year, $end_year);
    }
}