<?php

/**
 * ProfileAttendanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileAttendanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileAttendanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileAttendance');
    }
}