<?php

/**
 * ProfileCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileCourseTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object ProfileCourseTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('ProfileCourse');
  }

  public function deleteByCoursesIdsAndProfileId($courseIds, $profileId) {
    $query = $this->createQuery()
        ->delete()
        ->whereIn('course_id', $courseIds)
        ->andWhere("profile_id = ?", $profileId);

    return $query->execute();
  }

  public function deleteByCourseIdAndProfileIds($courseId, $profileIds = array()) {
    $query = $this->createQuery()
        ->delete()
        ->whereIn('profile_id', $profileIds)
        ->andWhere("course_id = ?", $courseId);

    return $query->execute();
  }

}