<?php

/**
 * ProfilePermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilePermissionTable extends Doctrine_Table
{
     static public $choices = array();
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilePermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilePermission');
    }

    public function getChoices()
    {
         $q = $this->createQuery('pp');         
         $choices = $q->execute();
         
         foreach($choices as $choice){
             self::$choices[$choice->getId()] = $choice->getName();
         }
         
        return self::$choices;
    }
}