<?php

/**
 * ProfileInterestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileInterestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileInterestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileInterest');
    }
}