<?php

/**
 * ProfileGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileGroup');
    }
}