<?php

/**
 * ProfileGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileGroupPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileGroupPermission');
    }
}