<?php

/**
 * ProfileCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileCalendar');
    }
}