<?php

/**
 * ProfileProfileGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileProfileGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileProfileGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileProfileGroup');
    }
}