<?php

/**
 * ProfileAwardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileAwardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileAwardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileAward');
    }

    public function getYears()
    {
        $start_year = date("Y", strtotime("- 70 years"));
        $end_year = date("Y");
        
        return range($start_year, $end_year);
    }
}