<?php

/**
 * ProfilePublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilePublicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilePublicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilePublication');
    }
}