<?php

/**
 * ProfileProgrammeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileProgrammeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileProgrammeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileProgramme');
    }

    public function deleteByProgramIdsAndStudentId($programIds, $studentId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('program_id', $programIds)
            ->andWhere("student_id = ?", $studentId);

        return $query->execute();
    }

}