<?php

/**
 * ProfileUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileUserPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileUserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileUserPermission');
    }
}