<?php

/**
 * ProgramLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramLevel');
    }
}