<?php

/**
 * PublicHolidayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicHolidayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicHolidayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicHoliday');
    }
}