<?php

/**
 * StaffMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaffMailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaffMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaffMailingList');
    }

    public function deleteByMailingListIdsAndStaffId($mailingListIds, $staffId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('mailing_list_id', $mailingListIds)
            ->andWhere('staff_id = ?', $staffId);

        return $query->execute();
    }
}