<?php

/**
 * StaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaffTable extends ProfileTable {

    const EMPLOYMENT_TYPE_FULL_TIME = 0;
    const EMPLOYMENT_TYPE_PART_TIME = 1;

    static public $employment_types = array(
        0 => 'Full time',
        1 => 'Part time'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object StaffTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Staff');
    }

    public function getEmploymentTypes() {
        return self::$employment_types;
    }

}