<?php

/**
 * StaffContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaffContactTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaffContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaffContact');
    }
}