<?php

/**
 * Staff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecollegeplus
 * @subpackage model
 * @author     Batanayi Matuku
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Staff extends BaseStaff
{

    public function __toString()
    {
        return $this->getUser()->__toString();
    }

    public function getCourses()
    {
        $courses = array();
        $staffCourses = $this->getStaffCourses();
        foreach ($staffCourses as $staffCourse)
        {
            $courses[$staffCourse->getCourse()->getId()] = $staffCourse->getCourse()->toArray();
        }

        return $courses;
    }

}
