<?php

/**
 * StateProvinceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StateProvinceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StateProvinceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StateProvince');
    }
}