<?php

/**
 * StudentCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentCourse');
    }

    public function deleteByCoursesIdsAndStudentId($courseIds, $studentId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('course_id', $courseIds)
            ->andWhere("student_id = ?", $studentId);

        return $query->execute();
    }

    public function deleteByCourseIdAndStudentIds($courseId, $studentIds = array())
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('student_id', $studentIds)
            ->andWhere("course_id = ?", $courseId);

        return $query->execute();
    }
}