<?php

/**
 * StudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentTable extends ProfileTable
{
    static public $enrollment_types = array(
        0 => 'Full time',
        1 => 'Part time'
    );
    static public $statuses = array(
        0 => 'Not registered',
        1 => 'Registered',
        2 => 'Application accepted (not registered)',
        3 => 'Application received',
        4 => 'Application rejected',
        5 => 'Expelled',
        6 => 'Alumin',
        7 => 'Withdrawn',
        8 => 'Dropped out'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object StudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Student');
    }

    public function getEnrollmentTypes()
    {
        return self::$enrollment_types;
    }

    public function getStatuses()
    {
        return self::$statuses;
    }

    public function retrieveByCourse($course_id = null)
    {
        $query = $this->createQuery('s')
            ->innerJoin('s.Courses c')
            ->where('c.id = ?', $course_id);

        return $query->execute();
    }

    public function retrieveByIds($ids = array())
    {
        if (count($ids) == 0)
        {
            return array();
        }
        $query = $this->createQuery('s')
            ->whereIn('s.id', $ids);

        return $query->execute();
    }
}