<?php

/**
 * StudentProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentProgram');
    }

    public function deleteByProgramIdsAndStudentId($programIds, $studentId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('program_id', $programIds)
            ->andWhere("student_id = ?", $studentId);

        return $query->execute();
    }

}