<?php

/**
 * StudentContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentContactTable extends ContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentContact');
    }
}