<?php

/**
 * StudentAttendanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentAttendanceTable extends Doctrine_Table
{
    static public $statuses = array(
        0 => 'Unrecorded',
        1 => 'Present',
        2 => 'Absent',
        3 => 'Tardy',
        4 => 'Excused'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object StudentAttendanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentAttendance');
    }

    public function getStatuses()
    {
        return self::$statuses;
    }

    public function retrieveByStudentAndAttendance($student_id = null, $attendance_id = null)
    {
        $query = $this->createQuery('sa')
            ->where('sa.student_id = ?', $student_id)
            ->addWhere('sa.attendance_id = ?', $attendance_id);

        return $query->fetchOne();
    }

    public function retrieveByAttendanceAndStatus($attendance_id = null, $status = null)
    {
        $query = $this->createQuery('sa')
            ->Where('sa.attendance_id = ?', $attendance_id);
        if (!is_null($status))
            $query = $query->addWhere('sa.status = ?', $status);

        return $query->execute();
    }

    public function createDefaultStudentAttendances($course = null)
    {
        foreach ($course->getStudents() as $student)
        {
            foreach ($course->getAttendances() as $attendance)
            {
                if (!is_object($this->retrieveByStudentAndAttendance($student->getId(), $attendance->getId())))
                {
                    $student_attendance = new StudentAttendance();
                    $student_attendance->setStatus();
                    $student_attendance->setStudent($student);
                    $student_attendance->setAttendance($attendance);
                    $student_attendance->save();
                }
            }
        }
    }

}