<?php

/**
 * StudentMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentMailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentMailingList');
    }

    public function deleteByStudentIdsAndMailingListsId($studentIds, $mailingListId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('student_id', $studentIds)
            ->andWhere('mailing_list_id = ?', $mailingListId);

        return $query->execute();
    }

    public function deleteByMailingListIdsAndStudentId($mailingListIds, $studentId)
    {
        $query = $this->createQuery()
            ->delete()
            ->whereIn('mailing_list_id', $mailingListIds)
            ->andWhere('student_id = ?', $studentId);

        return $query->execute();
    }    
}