<?php

/**
 * UserFolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserFolderTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object UserFolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserFolder');
    }

    public function findOrCreateOneByUser($user, $parentFolder)
    {
        if (!is_object($userFolder = $this->getInstance()->findOneByUserId($user->getId())))
        { 
            // save the user folder
            $folder = new Folder();
            $folder->setName($user->getName());
            $folder->setParentId($parentFolder->getId());
            $folder->getNode()->insertAsLastChildOf($parentFolder);
            
            // save the user folder linking
            $userFolder = new UserFolder();
            $userFolder->setUserId($user->getId());
            $userFolder->setFolderId($folder->getId());
            $userFolder->save();
        }
        return $userFolder->getFolder();
    }

}