<?php

/**
 * UserActivityFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserActivityFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserActivityFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserActivityFeed');
    }
}