# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
  
faq:
  url:   /faq
  param: { module: section, action: faq }
  
  
contact_us:
  url:   /contact/us
  param: { module: section, action: contactUs }
  
leadership:
  url:   /leadership
  param: { module: section, action: leadership }
  
mission:
  url:   /mission
  param: { module: section, action: mission }
  
modules:
  url:   /modules
  param: { module: section, action: modules }
  
students:
  url:   /students
  param: { module: section, action: students }
  
instructors:
  url:   /instructors
  param: { module: section, action: instructors }
  
philosophy:
  url:   /philosophy
  param: { module: section, action: philosophy }
  
work:
  url:   /work
  param: { module: section, action: work }
  
tos:
  url:   /tos
  param: { module: section, action: tos }
  
privacy_policy:
  url:   /privacy/policy
  param: { module: section, action: privacyPolicy }
  
home:
  url:   /
  param: { module: section, action: index }