generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DiscussionTopic
    theme:                 popup
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          discussion_topic
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:             ~
      fields:
        message:           { label: Post }
      form:
        display:           [type, subject, message]
      filter:
        class: false
      list:
        title:             My DiscussionGroup Topics
        display:           [type, message]
        sort:              [subject, asc]
        batch_actions:     []
        max_per_page:			 2
        actions:
          _new:            ~
      edit:
        title:             Edit DiscussionGroup Topic
        actions:
          _delete:         []
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New DiscussionGroup Topic
        actions:
          _delete:         []
          cancel:          []
          _save:           []