generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DiscussionTopic
    theme:                 normal
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          discussion_topic
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:             ~
      fields:
        type:              { label: Genre }
        message:           { label: Topic }
      form:
        display:           [type, subject, message]
      filter:
        class: false
      list:
        title:             My Discussion Topics
        display:           [type, message]
        sort:              [subject, asc]
        batch_actions:     []
        max_per_page:			 2
        actions:
          _new:            ~
      edit:
        title:             Edit Topic
        actions:
          _delete:         []
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Topic
        actions:
          _delete:         []
          cancel:          []
          _save:           { label: Post }
