generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DiscussionTopic
    theme:                 popup
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          discussion_topic
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:             ~
      fields:
        message:                  { label: Description }
        discussion_topic_type_id: { label: "Post Type" }
      form:
        display:           [discussion_topic_type_id, message]
      filter:
        class: false
      list:
        title:             My Discussion Topics
        display:           [discussion_topic_type_id, message]
        sort:              [subject, asc]
        batch_actions:     []
        max_per_page:			 2
        actions:
          _new:            ~
      edit:
        title:             Edit Discussion Topic
        actions:
          _delete:         []
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Discussion Topic
        actions:
          _delete:         []
          cancel:          []
          _save:           []