generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ioDoctrineMenuItem
    theme:                 ecollegeplus2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true    
    actions_base_class:    sfActions

    config:
      actions: ~
      form:
        display:            
          "Menu Details":     [ name, route, image, label, parent_id, requires_auth, permissions_list ]
      fields:
        requires_auth:        { label: Is Protected }
        permissions_list:     { label: Enabled Permissions }
      filter:
        class: false
      list:
        title:                Menu Items
        display:              [ name, route, requires_auth ]
        sort:                 [ name, asc ]
        batch_actions:        []
        max_per_page:         10 
        actions:
          _new: ~
      edit:
        title:                Edit Menu Item ~ %%name%%
        actions:
          _delete:            []
          cancel:             []
          done:               []
          _save:              []
      new:
        title:                New Menu Item
        actions:
          cancel:             []
          _save:              [ label: Proceed ]