all:
  stylesheets: [ secure.css, calendar.css ]
  
newSuccess:
  layout: false
  
editSuccess:
  layout: false
  
myScheduleSuccess:  
  stylesheets: [ secure.css, schedule.css, calendar.css ]
  javascripts: [ jquery/schedule.js ]