all:
  stylesheets: [ secure.css, course.css, student.css, profile.css ]
  
chooseSuccess:
  has_layout: false
  
calendarSuccess:  
  stylesheets: [ secure.css, schedule.css, calendar.css ]
  javascripts: [ jquery/schedule.js ]