generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Campus
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          campus
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:             ~
      fields:
      filter:
        class: false
      list:
        title:             Campuses
        display:           [ name, is_primary, address, city, postcode, country ]
        sort:              [ name, country_id, asc ]
        batch_actions:     []
        max_per_page:			 25
        actions:
          _new:            ~
      edit:
        title:             Edit Campus
        actions:
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Campus
        actions:
          cancel:          []
          _save:           []