generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sfGuardPermission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~      
      fields:
      form:
        display: [name, description, groups_list, users_list]
      list:
        title: User Permissions
        display: [=name, description, created_at, updated_at]
        batch_actions: []
        max_per_page: 3
        actions:
          _new: ~
      edit:
        title: Edit Permission - %%name%%
      new:
        title: New Permission