all:
  stylesheets: [calendar.css]
  
newSuccess:
  layout: false
  
editSuccess:
  layout: false
  
myCalendarSuccess:  
  stylesheets: [full_calendar_print, full_calendar, dashboard, -datepicker.css, calendar.css]
  javascripts: [jquery/full_calendar.js]