all:
  stylesheets: [calendar.css]
  
newSuccess:
  layout: false
  
editSuccess:
  layout: false
  
myScheduleSuccess:  
  stylesheets: [full_calendar_print, full_calendar, dashboard, calendar.css]
  javascripts: [jquery/full_calendar.js]