generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GradebookScale
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gradebook_scale
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:                  ~
      fields:
        code:                   { label: Grade }
        max_points:             { label: Max marks }
        min_points:             { label: Min marks }
      filter:
        class: false
      list:
        title:                  Gradebook Scale
        display:                [ code, min_points, max_points ]
        sort:                   [ min_points, asc ] 
        object_actions:       
        batch_actions:          []
        max_per_page:           10
        actions:
          _new:                 { label: "+ Add Gradebook Scale" }
      edit:
        actions:
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []