<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/21 20:39:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=tutorplus',
  'username' => 'tutorplus',
  'password' => '@%tut0rp1us#',
  'name' => 'doctrine',
)),);
