<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/09 16:55:40
sfConfig::add(array(
  'mod_notification_settings_enabled' => true,
  'mod_notification_settings_view_class' => 'sfPHP',
));
