<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/09 16:29:37
sfConfig::add(array(
  'mod_student_contact_enabled' => true,
  'mod_student_contact_view_class' => 'sfPHP',
));
