<?php
// auto-generated by sfViewConfigHandler
// date: 2012/09/22 09:14:28
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'landing' ? false : 'landing'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('elements.css', '', array ());
  $response->addStylesheet('tp.css', '', array ());
  $response->addStylesheet('left-menu.css', '', array ());
  $response->addStylesheet('form.css', '', array ());
  $response->addStylesheet('symfony.css', '', array ());
  $response->addStylesheet('jquery.simple-modal.css', '', array ());
  $response->addStylesheet('jquery-ui.css', '', array ());
  $response->addStylesheet('jquery-date-picker.css', '', array ());
  $response->addStylesheet('/tiny_mce/themes/simple/skins/default/ui.css', '', array ());
  $response->addStylesheet('colorbox/jquery.colorbox.css', '', array ());
  $response->addJavascript('jquery-1.6.2.min.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('jquery.validate.min.js', '', array ());
  $response->addJavascript('/sfFormExtraPlugin/js/double_list.js', '', array ());
  $response->addJavascript('/tiny_mce/tiny_mce.js', '', array ());
  $response->addJavascript('ecollegeplus.js', '', array ());
  $response->addJavascript('jquery.treeview.js', '', array ());
  $response->addJavascript('jquery.number_format.js', '', array ());
  $response->addJavascript('jquery.validate.numeric.js', '', array ());
  $response->addJavascript('jquery-ui.min.js', '', array ());
  $response->addJavascript('jquery.simplemodal.1.4.1.min.js', '', array ());
  $response->addJavascript('jquery.elastic.source.js', '', array ());
  $response->addJavascript('jquery.colorbox-min.js', '', array ());


