<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/09 16:55:21
sfConfig::add(array(
  'mod_profile_qualification_enabled' => true,
  'mod_profile_qualification_view_class' => 'sfPHP',
));
