<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/18 21:02:20
sfConfig::add(array(
  'mod_account_settings_enabled' => true,
  'mod_account_settings_view_class' => 'sfPHP',
));
