<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/09 16:04:06
sfConfig::add(array(
  'mod_account_settings_enabled' => true,
  'mod_account_settings_view_class' => 'sfPHP',
));
