generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 ecollegeplus2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sfGuardGroup
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        users_list:        { label: Recipients }
      filter:
        class: false
      list:
        title:             Groups
        display:           [ name, description ]
        sort:              [ name, created_at, asc ]
        batch_actions:     []
        max_per_page:			 10
        actions:
          _new: ~
      edit:
        title:             Edit Group: %%name%%
      new:
        title:             New Group:
