generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AssignmentGroup
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          assignment_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        weight:               { label: Weight (%) }
      filter:
        class: false
      list:
        title:                 Assignment Groups
        display:               [name, weight, course]
        sort:                  [name, asc]
        batch_actions:         []
        max_per_page:			     10
        actions:
          _new:                 ~
          myCourse:             { label: "< My Course", action: myCourse }
      edit:
        actions:
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []