generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Profile
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:                       ~
      actions:                      ~
      form:
        class:                      ProfileForm
        display:            
         "Personal Details":        [ first_name, middle_name, last_name, title, gender, birth_date ]
         "Academic Details":        [ high_school, studied_at, current_study, institution_id ]
         "Access Details":          [ email, password, password_confirmation, is_active ]
      filter:
        class: false
      list:                         ~
      edit:
        title:                      Account Settings
        actions:
          cancel:                   []
          done:                     []
          _save:                    []
      new:                          ~