indexSuccess:
  stylesheets: [main.css, sf_admin.css, jquery/jquery-ui.css, attendance.css]
  
showSuccess:
  stylesheets: [main.css, sf_admin.css, jquery/jquery-ui.css, attendance.css]

newSuccess:
  layout: false
  
editSuccess:
  layout: false