all:
  stylesheets: [course, student]
  
chooseSuccess:
  has_layout: false

currentSuccess:
  stylesheets: [profile.css, student.css]
  
calendarSuccess:  
  stylesheets: [full_calendar_print, full_calendar, dashboard, calendar.css]
  javascripts: [jquery/full_calendar.js]