generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EmailMessage
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          message_sent
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:               ~
      fields:
        to_email:            { label: To }
        updated_at:          { label: Date }
      form:
        class:                EmailMessage
      filter:
        class: false
      list:
        title:                Sent
        display:              [to_email, subject, updated_at]
        sort:                 [updated_at, desc]
        object_actions:       []
        batch_actions:        
          _delete:            ~
        max_per_page:			    10
        actions:              []