generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Student
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        password_again:      { label: "Confirm password" }
        permissions_list:    { label: Permissions }
      actions: ~
      form:
        class:                      StudentForm
        display:            
         "Personal Details":        [first_name, last_name, number, number, gender, date_of_birth]
         "Access Details":          [email_address, username, password, password_again, is_active]
         "Profile Permissions":     [permissions_list] 
      filter:
        class: false
      list:
        title:               Students
        display:             [first_name, last_name, email_address, number, gender]
        sort:                [number, asc]
        batch_actions:       []
        max_per_page:			   10
        actions:
          _new:              { label: "+ Add Student" }
      edit:
        title:               Edit Student ~ %%first_name%% %%last_name%%
        actions:
          _academic:         []
          _contact:          []
          cancel:            []
          done:              []
          _save:             []
      new:
        title:               New Student
        actions:
          cancel:            []
          _save:             { label: "Enroll Now!" }