generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Profile
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        password_again:             { label: "Password confirmation" }
        permissions_list:           { label: Permissions }
      actions: ~
      form:
        class:                      ProfileForm
        display:            
         "Personal Details":        [ first_name, middle_name, last_name, title, gender, birth_date ]
         "Access Details":          [ email, password, password_confirmation, is_active ]
         "Academic Details":        [ high_school, studied_at, current_study, institution_id ]
         "Student Permissions":     [ permissions_list ] 
      filter:
        class: false
      list:
        title:                      Students
        display:                    [ first_name, last_name, email, gender ]
        sort:                       [ first_name, asc ]
        batch_actions:              []
        max_per_page:			          10
        actions:
          _new:                     { label: "+ Add Student" }
      edit:
        title:                      Edit Student
        actions:
          _academic:                []
          _contact:                 []
          cancel:                   []
          done:                     []
          _save:                    []
      new:
        title:                      New Student
        actions:
          cancel:                   []
          _save:                    { label: "Enroll Now!" }