all:
  stylesheets: [course.css, student.css]
  has_layout: false
 
indexSuccess:
  has_layout: true
 
editSuccess:
  has_layout: true
 
newSuccess:
  has_layout: true
 
registerSuccess:
  layout: register