all:
  stylesheets:    [profile.css, discussion.css, jquery.jcrop.css]
  javascripts:    [jquery.jcrop.min.js, jquery.color.js]
  
newSuccess:
  has_layout:     false
  
editSuccess:
  has_layout:     false
 
indexSuccess:
  has_layout:     true