generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PaymentScheme
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          payment_scheme
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      filter:
        class: false
      list:
        title:                  Payment Schemes
        display:                [student, amount, _frequency, next_payment_date]
        sort:                   [frequency, asc]
        batch_actions:          []
        object_actions:
          _edit: ~
          _delete: ~
        max_per_page:			10
        actions:
          _new:                 { label: "+ Add Scheme" }
      form:
        display:
          "Details":            [student_id, amount, frequency, next_payment_date]
      edit:
        actions:
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []